#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: Run my GitHub Actions

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository to clone'
        required: true
        default: 'apache/spark'
      branch:
        description: 'Branch to checkout'
        required: true
        default: 'master'

jobs:
  run-my-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Spark repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.branch }}

      - name: Set up buf
        uses: bufbuild/buf-setup-action@v1.15.1

      - name: Build and push
        run: |
          dev/connect-gen-protos.sh

      - name: Upload test results to report
        uses: actions/upload-artifact@v3
        with:
          name: proto-output
          path: "python/pyspark/sql/connect/proto/**/*"

